services:
  mongodb:
    image: "mongo:${MONGO_VERSION:-latest}"
    container_name: twitch-bot-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 3s

  bot:
    build:
      context: .
      dockerfile: Dockerfile.python
      args:
        PACKAGE: "bot"
    container_name: twitch-bot
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGO__HOST=mongodb
      - MONGO__PORT=27017
      - MONGO__DB=twitch_bot
    env_file:
      - bot/.env
    ports:
      - "4343:4343"
    command: ["uv", "run", "bot/src/main.py"]

